# description of each layer
es_description="Embedded Server"
es_file_description="Embedded File Server"
es_auth_description="Embedded Authentication Server"
es_web_description="Embedded Web Server"
server_description="Server"
vmm_description="Virtual Machine Monitor"
workstation_description="Full Workstation of Doom"
es_devel_description="Embedded Development Server"

# layer dependencies for each layer
es_layers="es"
es_file_layers="es-file:es"
es_auth_layers="es-auth:es"
es_web_layers="es-web:es"
server_layers="server:es"
vmm_layers="vmm:server:es"
workstation_layers="workstation:vmm:server:es"
es_devel_layers="es-devel"
